#! /bin/bash

source $OPENSHIFT_ADVANCED_PYTHON_DIR/usr/python/versions/$version/bin/activate

nohup ipython notebook --no-browser --debug --notebook-dir=$OPENSHIFT_DATA_DIR/notebooks --ip=$OPENSHIFT_ADVANCED_PYTHON_IP --port=$OPENSHIFT_ADVANCED_PYTHON_PORT --profile-dir=$OPENSHIFT_REPO_DIR/.ipython/profile_default --keyfile=$OPENSHIFT_DATA_DIR/mycert.pem >> $OPENSHIFT_ADVANCED_PYTHON_LOG_DIR/notebook.log 2>&1 &
